window.KeyDates = (() => {
  const el=(id)=>document.getElementById(id),relation=(wert)=>Array.isArray(wert)?wert[0]:wert;
  const MONATE=["Jänner","Februar","März","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember"];
  let jahr=new Date().getFullYear(),rows=[];
  function farbe(kategorie){return /^#[0-9a-f]{6}$/i.test(kategorie?.farbe||"")?kategorie.farbe:"#46525b";}
  function monate(von,bis){return MONATE.slice(von,bis).map((name,index)=>{const monat=von+index;return{name,eintraege:rows.filter((row)=>Number(String(row.datum).slice(5,7))===monat+1).map((row)=>({id:row.id,tag:Number(String(row.datum).slice(8,10)),titel:row.titel,farbe:farbe(relation(row.kategorie))}))};});}
  function seitenDaten(){return[{untertitel:"Jänner – Juni",monate:monate(0,6)},{untertitel:"Juli – Dezember",monate:monate(6,12)}];}
  function seite(daten){const section=document.createElement("section");section.className="key-dates-sheet";section.innerHTML=`<header><h2>KEY DATES</h2><strong>${jahr}</strong><p>${daten.untertitel}</p></header>`;const grid=document.createElement("div");grid.className="key-dates-months";daten.monate.forEach((monat)=>{const block=document.createElement("section");block.className="key-dates-month";const h=document.createElement("h3");h.textContent=monat.name;block.appendChild(h);const list=document.createElement("div");list.className="key-dates-list";monat.eintraege.forEach((item)=>{const button=document.createElement("button");button.type="button";button.className="key-date-entry";button.dataset.id=item.id;button.style.setProperty("--key-date-color",item.farbe);button.innerHTML=`<span>${String(item.tag).padStart(2,"0")}</span><b></b>`;button.querySelector("b").textContent=item.titel;list.appendChild(button);});block.appendChild(list);grid.appendChild(block);});section.appendChild(grid);return section;}
  function rendern(){const container=el("kdSeiten");container.innerHTML="";seitenDaten().forEach((daten)=>container.appendChild(seite(daten)));}
  async function laden(){el("kdFehler").hidden=true;try{rows=await KeyDatesService.eintraege(jahr);rendern();}catch(error){console.error("Key Dates:",error);el("kdFehler").textContent=error.message;el("kdFehler").hidden=false;}}
  async function pdf(){const button=el("kdPdf"),text=button.textContent;button.disabled=true;button.textContent="Erstellt …";try{const blob=await KeyDatesPdfService.erstellen(jahr,seitenDaten());KeyDatesPdfService.speichern(blob,`Key-Dates-${jahr}.pdf`);}catch(error){AppFeedback.error(error.message);}finally{button.disabled=false;button.textContent=text;}}
  async function init(){const jahre=await KeyDatesService.jahre();el("kdJahr").innerHTML=jahre.map((wert)=>`<option value="${wert}">${wert}</option>`).join("");el("kdJahr").value=jahr;el("kdJahr").addEventListener("change",(event)=>{jahr=Number(event.target.value);laden();});el("kdPdf").addEventListener("click",pdf);el("kdDrucken").addEventListener("click",()=>window.print());el("kdSeiten").addEventListener("click",(event)=>{const entry=event.target.closest("[data-id]");if(!entry)return;Router.pendingStPeterDetailId=entry.dataset.id;Router.open("st-peter-mitterberg");});await laden();}
  return { init };
})();
