window.KeyDatesPdfService = (() => {
  const W=1240,H=1754;
  function pdf(bilder){const enc=new TextEncoder(),teile=[],offsets=[0];let len=0;const add=(v)=>{const b=typeof v==="string"?enc.encode(v):v;teile.push(b);len+=b.length;};const obj=(n,c)=>{offsets[n]=len;add(`${n} 0 obj\n${c}\nendobj\n`);};const pages=bilder.map((_,i)=>3+i*3);add("%PDF-1.4\n%\xE2\xE3\xCF\xD3\n");obj(1,"<< /Type /Catalog /Pages 2 0 R >>");obj(2,`<< /Type /Pages /Kids [${pages.map((id)=>`${id} 0 R`).join(" ")}] /Count ${bilder.length} >>`);bilder.forEach((bild,i)=>{const p=pages[i],img=p+1,c=p+2;obj(p,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im${i} ${img} 0 R >> >> /Contents ${c} 0 R >>`);offsets[img]=len;add(`${img} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${W} /Height ${H} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${bild.length} >>\nstream\n`);add(bild);add("\nendstream\nendobj\n");const stream=`q\n595.28 0 0 841.89 0 0 cm\n/Im${i} Do\nQ\n`;obj(c,`<< /Length ${enc.encode(stream).length} >>\nstream\n${stream}endstream`);});const xref=len,max=2+bilder.length*3;add(`xref\n0 ${max+1}\n0000000000 65535 f \n`);for(let i=1;i<=max;i+=1)add(`${String(offsets[i]).padStart(10,"0")} 00000 n \n`);add(`trailer\n<< /Size ${max+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);return new Blob(teile,{type:"application/pdf"});}
  function textZeilen(ctx,text,maxBreite,maxZeilen=2){const woerter=String(text||"").split(/\s+/),zeilen=[];let zeile="";woerter.forEach((wort)=>{const test=zeile?`${zeile} ${wort}`:wort;if(ctx.measureText(test).width<=maxBreite)zeile=test;else{if(zeile)zeilen.push(zeile);zeile=wort;}});if(zeile)zeilen.push(zeile);if(zeilen.length>maxZeilen){zeilen.length=maxZeilen;let letzte=zeilen[maxZeilen-1];while(letzte&&ctx.measureText(`${letzte}…`).width>maxBreite)letzte=letzte.slice(0,-1);zeilen[maxZeilen-1]=`${letzte}…`;}return zeilen;}
  async function zeichnen(jahr,seite){const canvas=document.createElement("canvas");canvas.width=W;canvas.height=H;const ctx=canvas.getContext("2d",{alpha:false});ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);ctx.textAlign="center";ctx.fillStyle="#243342";ctx.font="bold 38px Arial";ctx.fillText("KEY DATES",W/2,55);ctx.font="bold 26px Arial";ctx.fillText(String(jahr),W/2,91);ctx.font="20px Arial";ctx.fillText(seite.untertitel,W/2,122);const left=42,top=155,gapX=28,gapY=30,blockW=(W-left*2-gapX*2)/3,blockH=(H-top-45-gapY)/2;seite.monate.forEach((monat,index)=>{const col=index%3,row=Math.floor(index/3),x=left+col*(blockW+gapX),y=top+row*(blockH+gapY);ctx.textAlign="left";ctx.fillStyle="#243342";ctx.font="bold 24px Arial";ctx.fillText(monat.name,x,y+28);ctx.strokeStyle="#7e8a91";ctx.beginPath();ctx.moveTo(x,y+39);ctx.lineTo(x+blockW,y+39);ctx.stroke();let ey=y+67;(monat.eintraege||[]).forEach((item)=>{if(ey>y+blockH-34)return;ctx.fillStyle="#7f878c";ctx.font="16px Arial";ctx.fillText(String(item.tag).padStart(2,"0"),x,ey);ctx.fillStyle=item.farbe;ctx.font="18px Arial";const lines=textZeilen(ctx,item.titel,blockW-45,2);lines.forEach((line,i)=>ctx.fillText(line,x+42,ey+i*21));ey+=Math.max(25,lines.length*21+5);});});return new Promise((resolve,reject)=>canvas.toBlob(async(blob)=>blob?resolve(new Uint8Array(await blob.arrayBuffer())):reject(new Error("PDF-Seite konnte nicht erzeugt werden.")),"image/jpeg",.95));}
  async function erstellen(jahr,seiten){const bilder=[];for(const seite of seiten)bilder.push(await zeichnen(jahr,seite));return pdf(bilder);}
  function speichern(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  return { erstellen, speichern };
})();
